import { Market, Category, SubscriptionTier, Vendor, Product, Catalogue } from '../types';

export const INITIAL_MARKETS: Market[] = [
  {
    id: 'm-azam-1',
    name: 'Azam Cloth Market',
    slug: 'azam-cloth-market',
    city: 'Lahore',
    country: 'Pakistan',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'm-hall-2',
    name: 'Hall Road Commercial Hub',
    slug: 'hall-road',
    city: 'Lahore',
    country: 'Pakistan',
    is_active: true,
    created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'm-urdu-3',
    name: 'Urdu Bazaar Wholesale',
    slug: 'urdu-bazaar',
    city: 'Lahore',
    country: 'Pakistan',
    is_active: true,
    created_at: '2026-03-01T00:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'c-silk', name: 'Silk & Chiffon', slug: 'silk-chiffon', icon: '🧵', vendor_count: 14 },
  { id: 'c-lawn', name: 'Lawn & Cotton', slug: 'lawn-cotton', icon: '🌿', vendor_count: 28 },
  { id: 'c-embroidered', name: 'Embroidered', slug: 'embroidered', icon: '✨', vendor_count: 19 },
  { id: 'c-velvet', name: 'Velvet', slug: 'velvet', icon: '🎭', vendor_count: 8 },
  { id: 'c-linen', name: 'Linen & Khaddar', slug: 'linen-khaddar', icon: '🪡', vendor_count: 11 },
  { id: 'c-garments', name: 'Garments', slug: 'garments', icon: '👔', vendor_count: 22 },
  { id: 'c-net', name: 'Net & Organza', slug: 'net-organza', icon: '🌸', vendor_count: 9 },
  { id: 'c-jamawar', name: 'Jamawar', slug: 'jamawar', icon: '🔶', vendor_count: 6 },
];

export const INITIAL_TIERS: SubscriptionTier[] = [
  {
    id: 't-basic',
    name: 'basic',
    display_name: 'Basic',
    price_pkr: 2500,
    max_products: 10,
    max_catalogues: 1,
    has_analytics: false,
    has_verified_badge: false,
    has_featured_placement: false,
  },
  {
    id: 't-standard',
    name: 'standard',
    display_name: 'Standard',
    price_pkr: 5000,
    max_products: 30,
    max_catalogues: 3,
    has_analytics: true,
    has_verified_badge: true,
    has_featured_placement: false,
  },
  {
    id: 't-premium',
    name: 'premium',
    display_name: 'Premium',
    price_pkr: 9500,
    max_products: -1,
    max_catalogues: -1,
    has_analytics: true,
    has_verified_badge: true,
    has_featured_placement: true,
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'v-raza-silk',
    user_id: 'usr-raza',
    market_id: 'm-azam-1',
    tier_id: 't-standard',
    slug: 'raza-silk-house',
    shop_name: 'Raza Silk House',
    stall_number: 'Stall A-12, Ghee Mandi Bazaar',
    description: 'Premier wholesale supplier of premium Pure Pure Silk, Mysorie Silk, Chinese Crinkle Chiffon, and Printed Silk rolls in Azam Cloth Market since 1994. Direct mill importers and exporter quality fabrics.',
    logo_url: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=300&q=80',
    cover_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1200&q=80',
    whatsapp: '+923004123456',
    email: 'razasilk.azam@gmail.com',
    website: 'https://razasilk.pk',
    tags: ['Wholesale', 'Export Quality', 'MOQ 50m', 'Pure Silk', 'Direct Import'],
    categories: [INITIAL_CATEGORIES[0], INITIAL_CATEGORIES[6]], // Silk & Chiffon, Net & Organza
    is_verified: true,
    is_featured: true,
    status: 'active',
    profile_views: 1420,
    whatsapp_clicks: 348,
    email_clicks: 82,
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-07-28T12:00:00Z',
    products: [
      {
        id: 'p-1',
        vendor_id: 'v-raza-silk',
        name: 'Pure Rawsilk 80-Gram Dyed',
        description: '100% pure silk dyed in vibrant royal hues with soft drape and rich sheen.',
        fabric_type: 'Pure Silk',
        price_range: '₨1,200–1,500/m',
        moq: '50 metres',
        image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 1,
        created_at: '2026-01-12T00:00:00Z',
      },
      {
        id: 'p-2',
        vendor_id: 'v-raza-silk',
        name: 'Chinese Crinkle Chiffon Plain',
        description: 'Fine grade crinkle chiffon ideal for dupattas and bridal overlay kurtis.',
        fabric_type: 'Chiffon',
        price_range: '₨450–650/m',
        moq: '100 metres',
        image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 2,
        created_at: '2026-01-15T00:00:00Z',
      },
      {
        id: 'p-3',
        vendor_id: 'v-raza-silk',
        name: 'Digital Printed Silk Dupatta Rolls',
        description: 'Bespoke floral & Mughal motif digital prints on 100% silk twill.',
        fabric_type: 'Printed Silk',
        price_range: '₨1,800–2,400/roll',
        moq: '25 rolls',
        image_url: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 3,
        created_at: '2026-02-01T00:00:00Z',
      },
    ],
    catalogues: [
      {
        id: 'cat-raza-summer26',
        vendor_id: 'v-raza-silk',
        title: 'Silk & Chiffon Wholesale Lookbook',
        description: 'Complete summer 2026 color swatches, dye charts, and volume bulk discounts for boutique owners.',
        pdf_url: '/api/download/cat-raza-summer26',
        file_size_mb: 4.8,
        season: 'Summer 2026',
        download_count: 215,
        is_active: true,
        created_at: '2026-03-01T00:00:00Z',
      },
      {
        id: 'cat-raza-festive',
        vendor_id: 'v-raza-silk',
        title: 'Festive Pure Silk & Organza Collection',
        description: 'Heavy GSM festive dupattas, zari organza, and brocade swatches.',
        pdf_url: '/api/download/cat-raza-festive',
        file_size_mb: 6.2,
        season: 'Festive / Wedding 2026',
        download_count: 140,
        is_active: true,
        created_at: '2026-04-10T00:00:00Z',
      },
    ],
  },

  {
    id: 'v-al-hamza',
    user_id: 'usr-alhamza',
    market_id: 'm-azam-1',
    tier_id: 't-premium',
    slug: 'al-hamza-lawn-co',
    shop_name: 'Al-Hamza Lawn & Cotton Co.',
    stall_number: 'Stall C-7, Main Gate Azam Market',
    description: 'Leading manufacturer and wholesale distributor of 80x80 Lawn, Jacquard Cotton, Schiffli Embroidered Lawn, and Cambric Cotton suits. Supplying major retail brands across Pakistan, UAE, and UK.',
    logo_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    cover_url: 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=1200&q=80',
    whatsapp: '+923218889900',
    email: 'wholesale@alhamzalawn.com',
    website: 'https://alhamzalawn.com',
    tags: ['Wholesale', 'Factory Price', 'MOQ 100 suits', '80x80 Lawn', 'Brand Supplier'],
    categories: [INITIAL_CATEGORIES[1], INITIAL_CATEGORIES[2]], // Lawn & Cotton, Embroidered
    is_verified: true,
    is_featured: true,
    status: 'active',
    profile_views: 2890,
    whatsapp_clicks: 712,
    email_clicks: 195,
    created_at: '2026-01-05T08:00:00Z',
    updated_at: '2026-08-01T10:00:00Z',
    products: [
      {
        id: 'p-al-1',
        vendor_id: 'v-al-hamza',
        name: '3-Piece Schiffli Embroidered Lawn Set',
        description: 'Includes Schiffli front, lawn back/sleeves, and printed chiffon dupatta.',
        fabric_type: 'Lawn / Schiffli',
        price_range: '₨1,450–1,850/suit',
        moq: '50 suits',
        image_url: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 1,
        created_at: '2026-01-20T00:00:00Z',
      },
      {
        id: 'p-al-2',
        vendor_id: 'v-al-hamza',
        name: 'Unstitched Premium 80x80 Cambric Cotton',
        description: 'High thread count smooth combed cotton for daily lawn wear kurtis.',
        fabric_type: 'Cambric Cotton',
        price_range: '₨320–480/m',
        moq: '150 metres',
        image_url: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 2,
        created_at: '2026-02-10T00:00:00Z',
      },
      {
        id: 'p-al-3',
        vendor_id: 'v-al-hamza',
        name: 'Jacquard Weave Lawn 2-Piece Suits',
        description: 'Textured jacquard lawn shirt fabric paired with plain cotton trousers.',
        fabric_type: 'Jacquard Lawn',
        price_range: '₨1,100–1,350/suit',
        moq: '40 suits',
        image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 3,
        created_at: '2026-03-05T00:00:00Z',
      },
    ],
    catalogues: [
      {
        id: 'cat-al-vol1',
        vendor_id: 'v-al-hamza',
        title: 'Al-Hamza Lawn Vol 1 Wholesale Catalogue',
        description: 'Exclusive 40 design catalogue with price tier chart and sample swatch booking.',
        pdf_url: '/api/download/cat-al-vol1',
        file_size_mb: 8.5,
        season: 'Summer 2026',
        download_count: 489,
        is_active: true,
        created_at: '2026-02-15T00:00:00Z',
      },
      {
        id: 'cat-al-vol2',
        vendor_id: 'v-al-hamza',
        title: 'Schiffli & Chicken Kari Luxury Lawn Edition',
        description: 'High end boutique collection with detailed close-up stitch shots.',
        pdf_url: '/api/download/cat-al-vol2',
        file_size_mb: 11.2,
        season: 'Eid Ultra 2026',
        download_count: 310,
        is_active: true,
        created_at: '2026-05-01T00:00:00Z',
      },
    ],
  },

  {
    id: 'v-malik-velvet',
    user_id: 'usr-malik',
    market_id: 'm-azam-1',
    tier_id: 't-premium',
    slug: 'malik-velvet-traders',
    shop_name: 'Malik Velvet Traders',
    stall_number: 'Stall D-18, Silk Market Alley',
    description: 'Specialists in Micro Velvet 9000, 5000 Velvet, Embroidered Velvet Shawls, and Heavy Zardozi Bridal Velvet Fabric. Wholesale rolls and custom dyeing available.',
    logo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    cover_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80',
    whatsapp: '+923334445566',
    email: 'info@malikvelvet.pk',
    website: 'https://malikvelvet.pk',
    tags: ['Micro Velvet 9000', 'Bridal Fabric', 'Embroidered Shawls', 'Export Quality'],
    categories: [INITIAL_CATEGORIES[3], INITIAL_CATEGORIES[2]], // Velvet, Embroidered
    is_verified: true,
    is_featured: true,
    status: 'active',
    profile_views: 1850,
    whatsapp_clicks: 420,
    email_clicks: 96,
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-07-20T12:00:00Z',
    products: [
      {
        id: 'p-mv-1',
        vendor_id: 'v-malik-velvet',
        name: 'Micro Velvet 9000 Korean Quality',
        description: 'Ultra plush dark rich velvet roll, stretch resistant, non-shedding pile.',
        fabric_type: 'Micro Velvet 9000',
        price_range: '₨1,100–1,400/m',
        moq: '40 metres',
        image_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 1,
        created_at: '2026-01-25T00:00:00Z',
      },
      {
        id: 'p-mv-2',
        vendor_id: 'v-malik-velvet',
        name: 'Zari Tilla Embroidered Velvet Shawl Blank',
        description: 'Ready-to-cut velvet shawls with intricate four-sided antique tilla borders.',
        fabric_type: 'Embroidered Velvet',
        price_range: '₨3,500–5,000/piece',
        moq: '12 pieces',
        image_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 2,
        created_at: '2026-02-18T00:00:00Z',
      },
    ],
    catalogues: [
      {
        id: 'cat-malik-winter',
        vendor_id: 'v-malik-velvet',
        title: 'Velvet 9000 & Zari Shawl Catalogue',
        description: 'Winter 2026 master velvet swatch card with shade numbers 1-45.',
        pdf_url: '/api/download/cat-malik-winter',
        file_size_mb: 7.1,
        season: 'Winter 2026',
        download_count: 278,
        is_active: true,
        created_at: '2026-03-20T00:00:00Z',
      },
    ],
  },

  {
    id: 'v-zara-embroidery',
    user_id: 'usr-zara',
    market_id: 'm-azam-1',
    tier_id: 't-basic',
    slug: 'zara-embroidery-works',
    shop_name: 'Zara Embroidery Works',
    stall_number: 'Stall B-3, Circular Road Azam Market',
    description: 'Wholesale machine sequence, gota patti, thread embroidery on chiffon, organza, and net fabric. Specialized in custom order manufacturing for fashion houses.',
    logo_url: null,
    cover_url: null,
    whatsapp: '+923015556677',
    email: 'zaraembroidery.azam@gmail.com',
    tags: ['Embroidered', 'Custom Orders', 'Sequence Work', 'MOQ 30m'],
    categories: [INITIAL_CATEGORIES[2], INITIAL_CATEGORIES[6]], // Embroidered, Net & Organza
    is_verified: false,
    is_featured: false,
    status: 'active',
    profile_views: 640,
    whatsapp_clicks: 110,
    email_clicks: 24,
    created_at: '2026-02-01T08:00:00Z',
    updated_at: '2026-07-15T12:00:00Z',
    products: [
      {
        id: 'p-ze-1',
        vendor_id: 'v-zara-embroidery',
        name: 'Sequence Embroidery on Soft Organza',
        description: 'Pastel shades organza with shimmering sequence motif rows for formal wear.',
        fabric_type: 'Organza',
        price_range: '₨850–1,150/m',
        moq: '30 metres',
        image_url: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 1,
        created_at: '2026-02-10T00:00:00Z',
      },
    ],
    catalogues: [
      {
        id: 'cat-zara-vol1',
        vendor_id: 'v-zara-embroidery',
        title: 'Sequence & Thread Work Sample Book',
        description: 'PDF guide of 25 popular thread embroidery pattern codes.',
        pdf_url: '/api/download/cat-zara-vol1',
        file_size_mb: 3.4,
        season: 'All Seasons 2026',
        download_count: 82,
        is_active: true,
        created_at: '2026-03-01T00:00:00Z',
      },
    ],
  },

  {
    id: 'v-siddiqui-linen',
    user_id: 'usr-siddiqui',
    market_id: 'm-azam-1',
    tier_id: 't-standard',
    slug: 'siddiqui-linen-house',
    shop_name: 'Siddiqui Linen & Khaddar House',
    stall_number: 'Stall E-5, Kashmiri Bazaar Side',
    description: 'Kamalia Khaddar, Fine Woolen Linen, Cotton Viscose, and Slub Linen wholesale rolls. Authentic handloom and powerloom weaves directly from Kamalia and Faisalabad mills.',
    logo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    cover_url: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=1200&q=80',
    whatsapp: '+923029991122',
    email: 'contact@siddiquilinen.com',
    tags: ['Kamalia Khaddar', 'Slub Linen', 'Wholesale Rolls', 'Direct Mill Rates'],
    categories: [INITIAL_CATEGORIES[4]], // Linen & Khaddar
    is_verified: true,
    is_featured: false,
    status: 'active',
    profile_views: 980,
    whatsapp_clicks: 235,
    email_clicks: 45,
    created_at: '2026-02-15T08:00:00Z',
    updated_at: '2026-07-25T12:00:00Z',
    products: [
      {
        id: 'p-sl-1',
        vendor_id: 'v-siddiqui-linen',
        name: 'Pure Kamalia Khaddar 100% Cotton Unstitched',
        description: 'Traditional heavy weight Kamalia cotton khaddar for gents kurta shalwar.',
        fabric_type: 'Khaddar',
        price_range: '₨1,600–2,200/suit',
        moq: '20 suits',
        image_url: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 1,
        created_at: '2026-02-20T00:00:00Z',
      },
      {
        id: 'p-sl-2',
        vendor_id: 'v-siddiqui-linen',
        name: 'Soft Viscose Slub Linen Rolls',
        description: 'Breathable textured slub linen ideal for casual ladies kurtis and trousers.',
        fabric_type: 'Slub Linen',
        price_range: '₨380–520/m',
        moq: '100 metres',
        image_url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
        is_active: true,
        sort_order: 2,
        created_at: '2026-03-10T00:00:00Z',
      },
    ],
    catalogues: [
      {
        id: 'cat-siddiqui-khaddar',
        vendor_id: 'v-siddiqui-linen',
        title: 'Kamalia Khaddar Master Shade Card',
        description: 'Original color sample card featuring 32 earth tones.',
        pdf_url: '/api/download/cat-siddiqui-khaddar',
        file_size_mb: 5.1,
        season: 'Winter 2026',
        download_count: 164,
        is_active: true,
        created_at: '2026-04-01T00:00:00Z',
      },
    ],
  },

  {
    id: 'v-karimi-fabrics',
    user_id: 'usr-karimi',
    market_id: 'm-azam-1',
    tier_id: 't-basic',
    slug: 'karimi-fabrics',
    shop_name: 'Karimi Wholesale Fabrics',
    stall_number: 'Stall A-29, Inner Azam Square',
    description: 'Wholesale Jamawar, Brocade, Metallic Jacquard, and Banarsi Dupatta rolls. Onboarding verification pending.',
    logo_url: null,
    cover_url: null,
    whatsapp: '+923057778899',
    email: 'karimifabrics.lahore@gmail.com',
    tags: ['Jamawar', 'Banarsi', 'Pending Approval'],
    categories: [INITIAL_CATEGORIES[7]], // Jamawar
    is_verified: false,
    is_featured: false,
    status: 'pending',
    profile_views: 120,
    whatsapp_clicks: 15,
    email_clicks: 3,
    created_at: '2026-07-28T08:00:00Z',
    updated_at: '2026-07-28T08:00:00Z',
    products: [],
    catalogues: [],
  },
];
